
namespace {%Apps%}\Models;

use Cygnite\Foundation\Application;
use Cygnite\Database\Schema;
use Cygnite\Common\UrlManager\Url;
use Cygnite\Database\ActiveRecord;

/**
* This file is generated by Cygnite CLI Crud generator
*/

class %StaticModelName% extends ActiveRecord
{
    //your database connection name
    protected $database = '%databaseName%';

    // your table name here
    //protected $tableName = '%modelName%';

    protected $primaryKey = '{%primaryKey%}';

    //public $perPage = 5; // used to create pagination links

    public function __construct()
    {
        parent::__construct();
    }

    /*
    // Used to set pagination limit
    public function pageLimit()
    {
        return Url::segment(3);
    }
    */
}// End of the %StaticModelName% Model