namespace {%Apps%}\Models;

use Cygnite\Common\UrlManager\Url;
use Cygnite\Database\Cyrus\ActiveRecord;
use Cygnite\Validation\ValidationTrait;

/**
* This file is generated by Craft Console's Crud generator
*/

class %StaticModelName% extends ActiveRecord
{
    use ValidationTrait;

    //your database connection name
    protected $database = '%databaseName%';

    // your table name here
    //protected $tableName = '%modelName%';

    protected $primaryKey = '{%primaryKey%}';

    //public $perPage = 5; // used to create pagination links

    /**
    * Set Validation rules for Form
    *
    * @param $input
    * @return mixed
    */
    public $rules = [
{%rules%}
    ];

    public function __construct()
    {
        parent::__construct();
    }

    /*
    // Used to set pagination limit
    public function pageLimit()
    {
        return Url::segment(3);
    }
    */
}// End of the %StaticModelName% Model