
use Cygnite\Database\Migration;
use Cygnite\Database\Schema;

/**
* This file is generated by Cygnite Migration Command
* You may use up and down method to create migration
*/

class {%className%} extends Migration
{

    /**
     * Run the migrations up.
     *
     * @return void
     */
    public function up()
    {
        //Your schema to migrate
        
    }

    /**
     * Revert back your migrations.
     *
     * @return void
     */
    public function down()
    {
         //Roll back your changes done by up method.
         
    }
}// End of the Migration
